AplicacionIdentity/Models/ErrorViewModel.cs
namespace AplicacionIdentity.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AplicacionIdentity/Models/Registrar.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AplicacionIdentity.Models
{
    public class Registrar
    {
        [Required(ErrorMessage = "El Email es obligatorio!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "La contraseña es obligatorio!")]
        [StringLength(50, ErrorMessage ="La {0} debe ser minimo {2} caracteres y maximo {1}", MinimumLength = 5)]
        [DataType(DataType.Password)]
        [DisplayName("Contraseña")]
        public string Password { get; set; }

        [Required(ErrorMessage ="La confirmacion de la contraseña es obligatoria")]
        [Compare("Password", ErrorMessage = "Las contraseñas no coinciden!")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirmacion de Contraseña")]

        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Los nombres son obligatorios!")]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "Los apellidos son obligatorios!")]
        public string Apellidos { get; set; }
    }
}

AplicacionIdentity/Models/Usuario.cs
using Microsoft.AspNetCore.Identity;

namespace AplicacionIdentity.Models
{
    //Herencia
    public class Usuario : IdentityUser
    {
        public string nombres { get; set; }
        public string apellidos { get; set;}
    }
}

AplicacionIdentity/Controllers/CuentasController.cs
using AplicacionIdentity.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AplicacionIdentity.Controllers
{
    public class CuentasController : Controller
    {
        //Dependencias
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        //Constructor 

        public CuentasController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }


        public IActionResult Index()
        {
            return View();
        }

        //Registro de usuarios
        [HttpGet]
        //Vista del registro

        public async Task<IActionResult> Registro()
        {
            Registrar claseRegistrar = new Registrar();
            return View(claseRegistrar);
        }

        //Datos a enviar en el formulario

        [HttpPost]
        public async Task<IActionResult> Registro(Registrar claseRegistrar)
        {
            if(ModelState.IsValid)
            {
                var usuario = new Usuario
                {
                    UserName = claseRegistrar.Email,
                    Email = claseRegistrar.Email,
                    nombres = claseRegistrar.Nombres,
                    apellidos = claseRegistrar.Apellidos,

                };
                var resultado = await _userManager.CreateAsync(usuario, claseRegistrar. Password);
                await _signInManager.SignInAsync(usuario, isPersistent: false);
                return RedirectToAction("Index", "Home");
            }
            return View(claseRegistrar);

        }
    }
}

AplicacionIdentity/Controllers/HomeController.cs
using AplicacionIdentity.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AplicacionIdentity.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AplicacionIdentity/Views/Cuentas/Registro.cshtml
@model Registrar

@{
    ViewData["Title"] = "Registro de usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Formulario de Registro</h1>

<form asp-controller="Cuentas" asp-action="Registro" method="post" role="form" autocomplete="off">
    <div class="card-body">
        <div class="mb-3">
            <label asp-for="Nombres" class="form-control"></label>
            <input asp-for="Nombres" class="form-control" />
            <span asp-validation-for="Nombres" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Apellidos" class="form-control"></label>
            <input asp-for="Apellidos" class="form-control" />
            <span asp-validation-for="Apellidos" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Email" class="form-control"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Password" class="form-control"></label>
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="ConfirmPassword" class="form-control"></label>
            <input asp-for="ConfirmPassword" class="form-control" />
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>

        <div class ="mb-3">
            <button type="submit" class="btn btn-success">Registrar</button>
        </div>
    </div>


</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

AplicacionIdentity/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AplicacionIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicacionIdentity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicacionIdentity.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AplicacionIdentity | Prueba Unidad 4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuentas" asp-action="Registro">Registro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AplicacionIdentity - Alumnos: Brandon Vidal - Jose Montecinos | Profesor:  Alexis Fernández | Programación .NET <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>